#Requires -Version 7.0

<#
.SYNOPSIS
    Render CATALOG.md from the repo's generated manifest.json.

.DESCRIPTION
    Reads manifest.json (generated by scripts/generate-manifest.py — this script does
    not regenerate it, callers run generate-manifest.py first, as scripts/validate.ps1
    will do in T8) and renders the full asset tables — skills, instructions,
    commands, per platform and category — into CATALOG.md at the repo root, per D2:
    the root README stays a short orientation doc and CATALOG.md carries every
    hand-maintained count and table instead.

    Output must be byte-stable across runs given an unchanged manifest.json: ordinal
    (culture-invariant) sort order, utf8NoBOM encoding, LF line endings (enforced via
    .gitattributes) — so `scripts/validate.ps1` (T8) can regenerate CATALOG.md and
    fail on `git diff --exit-code` as its staleness gate.

    STATUS: documented stub now; becomes the first implemented script from this batch
    later in the plan (T6), per docs/requirements/canonical-repo.md §6 ("stub ->
    implemented in plan"). Invoking it today throws and exits non-zero.

    Shared conventions (docs/requirements/canonical-repo.md §6, binding for every
    lifecycle script):
      - Parameters: common surface is -Name, -TargetDir, -Force, -WhatIf, -Json.
        This script never repurposes their meaning. -Name is not applicable to a
        whole-catalog render and is accepted but unused. -TargetDir is the repo root
        to read manifest.json from and write CATALOG.md into (defaults to the current
        directory).
      - Safety: CATALOG.md is a generated file that is expected to be overwritten on
        every run; the implementation still backs up an existing CATALOG.md that
        wasn't itself generated from the current manifest.json before overwriting it,
        rather than clobbering unrecognized content silently. -Force skips the
        preview-only default and writes directly. All resolved paths are
        canonicalized and containment-checked against -TargetDir before any write.
      - Portability: no Windows-only APIs; output encoding utf8NoBOM; all table rows
        are ordinal (culture-invariant) sorted.

.PARAMETER Name
    Accepted for shared-surface consistency; unused (catalog generation is
    whole-repo, not per-skill).

.PARAMETER TargetDir
    Repo root containing manifest.json and receiving CATALOG.md. Defaults to the
    current directory.

.PARAMETER Force
    Write CATALOG.md directly instead of previewing the rendered output
    (preview/report-only default per the shared safety convention).

.PARAMETER WhatIf
    Standard PowerShell ShouldProcess preview — prints the rendered CATALOG.md
    without writing it.

.PARAMETER Json
    Emit the parsed table data as JSON instead of rendering markdown.

.OUTPUTS
    CATALOG.md written to -TargetDir (default behavior), a console preview
    (-WhatIf), or a JSON object (-Json) of the table data that would be rendered.

.NOTES
    Exit codes:
      0 = success — CATALOG.md written (or, in preview mode, nothing prevented preview)
      1 = validation failure — e.g. manifest.json missing or fails
          `generate-manifest.py --validate --json`
      2 = execution error — unexpected exception (I/O failure, malformed manifest, etc.)

    Currently unimplemented: this stub always throws (exit code 2) regardless of
    parameters, so accidental execution fails loudly.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$Name = '',

    [string]$TargetDir = '.',

    [switch]$Force,

    [switch]$Json
)

throw "TODO: not implemented"
