#Requires -Version 7.0

<#
.SYNOPSIS
    Render CATALOG.md from the repo's generated manifest.json.

.DESCRIPTION
    Reads manifest.json (generated by scripts/generate-manifest.py — this script does
    not regenerate it, callers run generate-manifest.py first, as scripts/validate.ps1
    does in T8) and renders the full asset tables — skills, instructions,
    commands, per platform and category — into CATALOG.md at the repo root, per D2:
    the root README stays a short orientation doc and CATALOG.md carries every
    hand-maintained count and table instead.

    Output is byte-stable across runs given an unchanged manifest.json: ordinal
    (culture-invariant) sort order via [System.StringComparer]::Ordinal, utf8NoBOM
    encoding, LF line endings written explicitly and pinned via .gitattributes — so
    `scripts/validate.ps1` (T8) can regenerate CATALOG.md and fail on
    `git diff --exit-code` as its staleness gate.

    Renders faithfully whatever manifest.json['categories'] contains, including
    near-duplicate category names (e.g. "Tooling & DevOps" vs "DevOps & Tooling") —
    this script never merges, dedupes, or reinterprets category data. Category
    consolidation is a skill-frontmatter change and out of scope for a read-only
    catalog renderer (docs/reorg/charter.md N1).

    Content sections, in order:
      1. Skills — one section per platform (claude, codex, gemini), each with one
         table per category in manifest['categories'] curated order (categories with
         zero skills for that platform are omitted). Rows sorted ordinally by skill
         name. Each row: name (linked, backtick-wrapped for audit.ps1 catalog-parity
         matching), description, and an "Also in" column listing the other platforms
         that carry a skill of the same name.
      2. Instructions — one table per platform (claude, codex, gemini) — OQ4:
         Codex/Gemini instructions exist but were uncounted before this script;
         included here.
      3. Commands — global claude/commands/*.md slash commands.
      4. Shared assets — one listing per shared/ asset class (prompts, workflows,
         configs, plugins), excluding each class's own README.md.

    Deliberately NOT backtick-wrapped: command names, instruction names, and shared
    asset filenames. audit.ps1's CATALOG-parity reverse check treats any backtick
    code-span matching `[a-z0-9][a-z0-9-]{2,}` as a claimed skill slug and verifies it
    against the manifest's claude+codex skill names; only actual skill-name cells use
    backticks so that check stays meaningful in both directions.

    Shared conventions (docs/requirements/canonical-repo.md §6, binding for every
    lifecycle script):
      - Parameters: common surface is -Name, -TargetDir, -Force, -WhatIf, -Json.
        This script never repurposes their meaning. -Name is not applicable to a
        whole-catalog render and is accepted but unused. -TargetDir is the repo root
        to read manifest.json from and write CATALOG.md into (defaults to the current
        directory).
      - Safety: CATALOG.md is a generated file that is expected to be overwritten on
        every run; the implementation still backs up an existing CATALOG.md that
        doesn't carry this script's generated-file marker before overwriting it,
        rather than clobbering unrecognized content silently. -Force skips the
        preview-only default and writes directly. All resolved paths are
        canonicalized and containment-checked against -TargetDir before any write.
      - Portability: no Windows-only APIs; output encoding utf8NoBOM; all table rows
        are ordinal (culture-invariant) sorted.

.PARAMETER Name
    Accepted for shared-surface consistency; unused (catalog generation is
    whole-repo, not per-skill).

.PARAMETER TargetDir
    Repo root containing manifest.json and receiving CATALOG.md. Defaults to the
    current directory.

.PARAMETER Force
    Write CATALOG.md directly instead of previewing the rendered output
    (preview/report-only default per the shared safety convention).

.PARAMETER WhatIf
    Standard PowerShell ShouldProcess preview — prints the rendered CATALOG.md
    without writing it.

.PARAMETER Json
    Emit the parsed table data as JSON to stdout instead of rendering markdown; does
    not write CATALOG.md.

.OUTPUTS
    CATALOG.md written to -TargetDir (default behavior with -Force), a console
    preview (default without -Force, or -WhatIf), or a JSON object (-Json) of the
    table data that would be rendered.

.NOTES
    Exit codes:
      0 = success — CATALOG.md written, previewed, or JSON emitted
      1 = validation failure — manifest.json missing, or
          `generate-manifest.py --validate --json` reports a non-zero exit
      2 = execution error — unexpected exception (I/O failure, malformed manifest, etc.)

.EXAMPLE
    ./scripts/generate-catalog.ps1 -Force

.EXAMPLE
    ./scripts/generate-catalog.ps1 -WhatIf

.EXAMPLE
    ./scripts/generate-catalog.ps1 -Json
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$Name = '',

    [string]$TargetDir = '.',

    [switch]$Force,

    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:GeneratedMarker = '<!-- GENERATED FILE'

# Ordinal sort helper (culture-invariant determinism) — mirrors audit.ps1, with an
# extra null-guard: `@($null)` in PowerShell produces a *one-element* array holding
# $null (not an empty array) when a filtering pipeline upstream (e.g.
# `Get-ChildItem | Where-Object {...}`) matches nothing. Piping through
# `Where-Object { $null -ne $_ }` before `@()` avoids manufacturing a phantom
# element that would otherwise render as a blank-named row downstream.
function Sort-Ordinal {
    param([string[]]$Items)
    $arr = @($Items | Where-Object { $null -ne $_ })
    [Array]::Sort($arr, [System.StringComparer]::Ordinal)
    return $arr
}

# Safely enumerate property names from a ConvertFrom-Json object — the
# `.PSObject.Properties.Name` shortcut throws under Set-StrictMode when the object
# has zero properties. Mirrors audit.ps1.
function Get-PropertyNames {
    param($Object)
    $names = [System.Collections.Generic.List[string]]::new()
    if ($null -ne $Object) {
        foreach ($p in $Object.PSObject.Properties) { $names.Add($p.Name) }
    }
    return $names.ToArray()
}

# Resolve a Python interpreter explicitly (cross-platform). Mirrors audit.ps1.
function Get-PythonExe {
    foreach ($candidate in 'python3', 'python') {
        $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($cmd) { return $cmd.Source }
    }
    throw "No Python interpreter found on PATH (tried python3, python)."
}

# Canonicalize a child path and verify it stays contained under $Root (no traversal
# via a crafted -TargetDir).
function Resolve-ContainedPath {
    param([string]$Root, [string]$ChildName)
    $full = [System.IO.Path]::GetFullPath((Join-Path $Root $ChildName))
    $rootFull = [System.IO.Path]::GetFullPath($Root)
    $rootWithSep = $rootFull.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    if (-not ($full.StartsWith($rootWithSep, [System.StringComparison]::Ordinal)) -and $full -ne $rootFull) {
        throw "Path '$ChildName' escapes -TargetDir '$Root'."
    }
    return $full
}

# Markdown table-cell escaping: pipes and newlines break table rows.
function Format-Cell {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    $flat = ($Text -replace '\r?\n', ' ') -replace '\|', '\|'
    $flat = $flat.Trim()
    if ($flat.Length -gt 220) {
        $flat = $flat.Substring(0, 217) + '...'
    }
    return $flat
}

# Extract a human description from a claude/commands/*.md file: frontmatter
# `description:` field if present, else the first non-empty, non-heading line
# after the leading `# ` title.
function Get-CommandDescription {
    param([string]$Path)
    $lines = [System.IO.File]::ReadAllLines($Path)
    if ($lines.Length -gt 0 -and $lines[0].TrimEnd() -eq '---') {
        for ($i = 1; $i -lt $lines.Length; $i++) {
            if ($lines[$i].TrimEnd() -eq '---') { break }
            if ($lines[$i] -match '^description:\s*(.*)$') {
                return $Matches[1].Trim().Trim('"').Trim("'")
            }
        }
    }
    $sawHeading = $false
    foreach ($line in $lines) {
        $t = $line.Trim()
        if ($t -eq '' -or $t -eq '---') { continue }
        if ($t.StartsWith('#')) { $sawHeading = $true; continue }
        if ($t.StartsWith('>')) { $t = $t.Substring(1).Trim() }
        if ($t -eq '') { continue }
        return $t
    }
    if ($sawHeading) { return '' }
    return ''
}

$exitCode = 0
$script:ExecError = $null

try {
    $resolvedTargetDir = (Resolve-Path -LiteralPath $TargetDir).Path
    $manifestPath = Resolve-ContainedPath -Root $resolvedTargetDir -ChildName 'manifest.json'
    $catalogPath  = Resolve-ContainedPath -Root $resolvedTargetDir -ChildName 'CATALOG.md'

    if (-not (Test-Path -LiteralPath $manifestPath)) {
        Write-Host "generate-catalog: manifest.json not found at $manifestPath"
        Write-Host "  run: python scripts/generate-manifest.py"
        exit 1
    }

    $generator = Join-Path $resolvedTargetDir 'scripts/generate-manifest.py'
    if (-not (Test-Path -LiteralPath $generator)) {
        throw "generator not found: $generator"
    }
    $pythonExe = Get-PythonExe
    & $pythonExe @($generator, '--validate', '--json') | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "generate-catalog: generate-manifest.py --validate --json failed (exit $LASTEXITCODE)"
        exit 1
    }

    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    $categories = @($manifest.categories)
    $platformOrder = @('claude', 'codex', 'gemini')

    # ---- Gather per-platform skill/instruction name sets (ordinal-sorted) --------
    $platformSkills = @{}
    $platformSkillNames = @{}
    $platformInstructions = @{}
    $platformInstructionNames = @{}
    foreach ($p in $platformOrder) {
        $skills = $manifest.platforms.$p.skills
        $platformSkills[$p] = $skills
        $platformSkillNames[$p] = Sort-Ordinal (Get-PropertyNames $skills)

        $instr = $manifest.platforms.$p.instructions
        $platformInstructions[$p] = $instr
        $platformInstructionNames[$p] = Sort-Ordinal (Get-PropertyNames $instr)
    }

    # ---- Build the JSON-able data model (also used for -Json output) -------------
    $data = [ordered]@{
        schemaVersion   = $manifest.schemaVersion
        sourceGenerated = $manifest.generated
        categories      = $categories
        platforms       = [ordered]@{}
        commands        = @()
        sharedAssets    = [ordered]@{}
    }

    foreach ($p in $platformOrder) {
        $skillRows = foreach ($n in $platformSkillNames[$p]) {
            $s = $platformSkills[$p].$n
            $others = @($platformOrder | Where-Object {
                $_ -ne $p -and $platformSkillNames[$_] -contains $n
            })
            [ordered]@{
                name        = $n
                category    = $s.category
                description = $s.description
                path        = "$p/skills/$n/SKILL.md"
                alsoIn      = $others
            }
        }
        $instrRows = foreach ($n in $platformInstructionNames[$p]) {
            $inst = $platformInstructions[$p].$n
            [ordered]@{
                name        = $n
                description = $inst.description
                model       = if ($inst.PSObject.Properties.Name -contains 'model') { $inst.model } else { $null }
                path        = "$p/instructions/$n.md"
            }
        }
        $data.platforms[$p] = [ordered]@{
            skills       = @($skillRows)
            instructions = @($instrRows)
        }
    }

    # ---- Commands (claude/commands/*.md — global slash commands) -----------------
    $commandsDir = Join-Path $resolvedTargetDir 'claude/commands'
    $commandNames = @()
    if (Test-Path -LiteralPath $commandsDir) {
        $commandNames = Sort-Ordinal (
            Get-ChildItem -LiteralPath $commandsDir -File -Filter '*.md' |
                ForEach-Object { $_.BaseName }
        )
    }
    $data.commands = foreach ($n in $commandNames) {
        $cmdPath = Join-Path $commandsDir "$n.md"
        [ordered]@{
            name        = $n
            description = Get-CommandDescription -Path $cmdPath
            path        = "claude/commands/$n.md"
        }
    }

    # ---- Shared assets (per class, excluding each class's own README.md) ---------
    $sharedClasses = @('prompts', 'workflows', 'configs', 'plugins')
    foreach ($class in $sharedClasses) {
        $classDir = Join-Path $resolvedTargetDir "shared/$class"
        $files = @()
        if (Test-Path -LiteralPath $classDir) {
            $files = Sort-Ordinal (
                Get-ChildItem -LiteralPath $classDir -File |
                    Where-Object { $_.Name -ne 'README.md' } |
                    ForEach-Object { $_.Name }
            )
        }
        $data.sharedAssets[$class] = @($files | ForEach-Object {
            [ordered]@{ name = $_; path = "shared/$class/$_" }
        })
    }

    # -------------------------------------------------------------------------
    # -Json: emit the data model and stop (no file write).
    # -------------------------------------------------------------------------
    if ($Json) {
        $data | ConvertTo-Json -Depth 10
        exit 0
    }

    # ---------------------------------------------------------------------------
    # Render markdown
    # ---------------------------------------------------------------------------
    $lines = [System.Collections.Generic.List[string]]::new()
    $add = { param($s) $lines.Add($s) }

    & $add '<!-- GENERATED FILE — DO NOT HAND-EDIT.'
    & $add '     Run: pwsh ./scripts/generate-catalog.ps1 -Force'
    & $add "     Source: manifest.json (generated: $($manifest.generated), schemaVersion: $($manifest.schemaVersion))"
    & $add '-->'
    & $add ''
    & $add '# Catalog'
    & $add ''
    & $add 'Full generated asset index for ai-agent-kit — skills, instructions, commands,'
    & $add 'and shared assets, across all vendors. See the root `README.md` for the mission'
    & $add 'and orientation doc; this file is the single generated source of every table and'
    & $add 'count (G5, `docs/requirements/canonical-repo.md`).'
    & $add ''
    & $add '**Known data-quality note:** `manifest.json`''s category list carries two'
    & $add 'near-duplicate categories — `Tooling & DevOps` and `DevOps & Tooling` — retained'
    & $add 'unmerged here on purpose; this renderer never edits or dedupes category data.'
    & $add 'See the PR that introduced this file for counts and follow-up.'
    & $add ''

    foreach ($p in $platformOrder) {
        $label = $p.Substring(0,1).ToUpperInvariant() + $p.Substring(1)
        & $add "## $label Skills"
        & $add ''
        $anyForPlatform = $false
        $seenNames = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
        foreach ($cat in $categories) {
            $rows = @($data.platforms[$p].skills | Where-Object { $_.category -eq $cat })
            if ($rows.Count -eq 0) { continue }
            $anyForPlatform = $true
            & $add "### $cat"
            & $add ''
            & $add '| Skill | Description | Also in |'
            & $add '|---|---|---|'
            foreach ($r in $rows) {
                [void]$seenNames.Add($r.name)
                $also = if ($r.alsoIn.Count -gt 0) { ($r.alsoIn -join ', ') } else { '—' }
                & $add "| [``$($r.name)``]($($r.path)) | $(Format-Cell $r.description) | $also |"
            }
            & $add ''
        }
        # Defensive: any skill whose category isn't in the curated list (data drift)
        # still gets a row instead of being silently dropped.
        $orphans = @($data.platforms[$p].skills | Where-Object { -not $seenNames.Contains($_.name) })
        if ($orphans.Count -gt 0) {
            $anyForPlatform = $true
            & $add '### (uncategorized / category not in curated list)'
            & $add ''
            & $add '| Skill | Category | Description | Also in |'
            & $add '|---|---|---|---|'
            foreach ($r in (Sort-Ordinal ($orphans | ForEach-Object { $_.name })) ) {
                $row = $orphans | Where-Object { $_.name -eq $r } | Select-Object -First 1
                $also = if ($row.alsoIn.Count -gt 0) { ($row.alsoIn -join ', ') } else { '—' }
                & $add "| [``$($row.name)``]($($row.path)) | $($row.category) | $(Format-Cell $row.description) | $also |"
            }
            & $add ''
        }
        if (-not $anyForPlatform) {
            & $add '_No skills for this platform._'
            & $add ''
        }
    }

    foreach ($p in $platformOrder) {
        $label = $p.Substring(0,1).ToUpperInvariant() + $p.Substring(1)
        & $add "## $label Instructions"
        & $add ''
        $rows = @($data.platforms[$p].instructions)
        if ($rows.Count -eq 0) {
            & $add '_No instructions for this platform._'
            & $add ''
            continue
        }
        & $add '| Instruction | Description | Model |'
        & $add '|---|---|---|'
        foreach ($r in $rows) {
            $model = if ($r.model) { $r.model } else { '—' }
            & $add "| [$($r.name)]($($r.path)) | $(Format-Cell $r.description) | $model |"
        }
        & $add ''
    }

    & $add '## Commands'
    & $add ''
    & $add 'Global slash commands under `claude/commands/`. Skill-bundled commands are'
    & $add 'listed on their owning skill (see `has_commands` in `manifest.json`) rather'
    & $add 'than duplicated here.'
    & $add ''
    if ($data.commands.Count -eq 0) {
        & $add '_No global commands found._'
        & $add ''
    }
    else {
        & $add '| Command | Description |'
        & $add '|---|---|'
        foreach ($r in $data.commands) {
            & $add "| [/$($r.name)]($($r.path)) | $(Format-Cell $r.description) |"
        }
        & $add ''
    }

    & $add '## Shared Assets'
    & $add ''
    & $add 'Vendor-neutral assets under `shared/` (`docs/requirements/canonical-repo.md` D1).'
    & $add 'Each class''s own `README.md` documents its conventions and is not listed as an'
    & $add 'asset here.'
    & $add ''
    foreach ($class in $sharedClasses) {
        $label = $class.Substring(0,1).ToUpperInvariant() + $class.Substring(1)
        & $add "### $label"
        & $add ''
        $files = @($data.sharedAssets[$class])
        if ($files.Count -eq 0) {
            & $add '_README only — no assets yet._'
        }
        else {
            foreach ($f in $files) {
                & $add "- [$($f.name)]($($f.path))"
            }
        }
        & $add ''
    }

    $rendered = ($lines -join "`n") + "`n"

    # -------------------------------------------------------------------------
    # Preview vs write
    # -------------------------------------------------------------------------
    if (-not $Force) {
        Write-Output $rendered
        exit 0
    }

    if (-not $PSCmdlet.ShouldProcess($catalogPath, 'Write CATALOG.md')) {
        Write-Output $rendered
        exit 0
    }

    if (Test-Path -LiteralPath $catalogPath) {
        $existing = [System.IO.File]::ReadAllText($catalogPath)
        if (-not $existing.StartsWith($script:GeneratedMarker)) {
            $backupPath = "$catalogPath.bak-" + [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
            Copy-Item -LiteralPath $catalogPath -Destination $backupPath -Force
            Write-Host "generate-catalog: backed up unrecognized existing CATALOG.md to $backupPath"
        }
    }

    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($catalogPath, $rendered, $utf8NoBom)
    Write-Host "generate-catalog: wrote $catalogPath"
}
catch {
    $script:ExecError = $_
    $exitCode = 2
    [Console]::Error.WriteLine("generate-catalog: execution failure: $($script:ExecError)")
}

exit $exitCode
