#Requires -Version 7.0
<#
.SYNOPSIS
    Local pre-PR validation gate for the ai-agent-kit archive (P2, as modified:
    local, not GitHub Actions).

.DESCRIPTION
    Wraps two existing scripts into a single pass/fail gate:

      1. Catalog staleness — regenerates CATALOG.md from the manifest.json
         currently on disk (the *committed* manifest — this script does not
         regenerate manifest.json first; manifest freshness is a separate,
         independent check, see below) via `generate-catalog.ps1 -Force`, then
         compares the regenerated bytes against the original CATALOG.md bytes.
         Any difference is an [error] finding ('catalog-staleness') — this is the
         byte-level equivalent of `git diff --exit-code -- CATALOG.md`, computed
         without ever leaving a diff in the working tree (see "Working tree
         safety" below). [error]
      2. `audit.ps1` — run as a child process (`-Json`) and its findings/exit
         code folded into this script's own result. This is deliberately the
         *only* place manifest.json's freshness is checked: audit.ps1 already
         regenerates manifest.json to a temp path and diffs it against the
         committed copy with the volatile `generated` timestamp field excluded
         (docs/requirements/canonical-repo.md §6). Re-implementing that check
         here as a second, timestamp-naive `git diff` would false-positive every
         day after midnight — an explicit, load-bearing requirement of this
         script's design. Audit's info-severity findings (Claude<->Codex mirror
         gaps, charter §5, and missing diagram.html) never fail this gate;
         audit's own exit-code contract (0 = clean/warnings-only, 1 = any
         error-severity finding, 2 = execution failure) is propagated as-is.

      3. Changelog staleness — every release tag (`v*`) must have a matching
         `## [<version>]` section in CHANGELOG.md. This is deliberately NOT the
         byte-equality check used for CATALOG.md in (1): CATALOG.md derives from
         the committed manifest.json, so regenerate-and-compare is stable, but
         CHANGELOG.md derives from HEAD — any commit invalidates it, and the very
         commit that refreshes it invalidates it again, so byte-equality would be
         unsatisfiable and the gate would never be green. Only the *released*
         sections are immutable (each derives from `prevTag..tag`), so only their
         presence is asserted; the volatile `[Unreleased]` section is ignored.
         This is the STALE CHANGELOG condition defined by the Release-Automation
         Standard (claude/skills/github/sub-skills/release-init/SKILL.md). [error]

    Working tree safety: CATALOG.md is regenerated in place (via -Force) purely
    to obtain byte-for-byte output identical to what a committed regeneration
    would produce, then its original bytes (captured before the regeneration,
    or "did not exist" if there was no committed CATALOG.md) are restored in a
    `finally` block — unconditionally, whether the check passes, fails, or
    throws. A clean working tree is bit-for-bit clean after this script runs;
    a dirty one is restored to exactly the same dirty state it started in. No
    git commands are used for this restoration (plain file bytes in, file bytes
    out), so it holds regardless of the target's git index/staging state.

    Both `generate-catalog.ps1` and `audit.ps1` end their own scripts with
    `exit $code` — dot-sourcing either would terminate this script's process
    outright, so both are invoked as child `pwsh` processes (explicit
    interpreter + argument array, no shell string interpolation, per the
    requirements §6 subprocess convention).

.PARAMETER RepoRoot
    Archive root to validate. Defaults to the parent of the directory holding
    this script. Aliased -TargetDir for the shared parameter-surface
    convention (docs/requirements/canonical-repo.md §6); this script mirrors
    audit.ps1's precedent of naming its primary parameter -RepoRoot since, like
    audit.ps1, it operates read-mostly over the whole archive rather than
    writing into a single named target.

.PARAMETER Json
    Emit a single JSON document (catalog-staleness result + audit's own -Json
    payload + summary + exit code + runtime) to stdout instead of a console
    summary table.

.OUTPUTS
    Console summary table (default) or JSON (-Json).

.NOTES
    Exit codes (requirements §6, mirrors audit.ps1's refinement):
      0  clean — CATALOG.md and CHANGELOG.md are fresh and audit.ps1 exited 0
      1  findings — CATALOG.md is stale, CHANGELOG.md is missing a released
         section, and/or audit.ps1 exited 1 (error-severity findings present)
      2  execution failure — could not complete validation (missing
         prerequisite script, no pwsh/python on PATH, unexpected exception, or
         audit.ps1 itself exited 2)

    Applicable shared conventions (docs/requirements/canonical-repo.md §6):
      - Parameters: -Name and -Force/-WhatIf are not applicable — this script
        is read-only over the archive (it never leaves a net change on disk,
        see "Working tree safety" above) and operates on the whole repo, not a
        single named asset. -TargetDir is honored via the -RepoRoot alias.
        -Json is honored directly.
      - Safety: no net mutation — see "Working tree safety" above. Runtime
        target: <60s locally.
      - Subprocess: `generate-catalog.ps1` and `audit.ps1` are invoked via an
        explicitly resolved `pwsh` executable + argument array; `audit.ps1` in
        turn resolves `python`/`python3` the same way internally.
      - Portability: no Windows-only APIs; ordinal (culture-invariant) byte/text
        comparison; utf8NoBOM preserved (bytes are round-tripped verbatim, never
        re-encoded).

.EXAMPLE
    ./scripts/validate.ps1

.EXAMPLE
    ./scripts/validate.ps1 -Json
#>
[CmdletBinding()]
param(
    [Alias('TargetDir')]
    [string]$RepoRoot,

    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

if (-not $RepoRoot) {
    $RepoRoot = Split-Path -Parent $PSScriptRoot
}
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path

# Resolve pwsh explicitly (cross-platform) — mirrors audit.ps1's Get-PythonExe.
function Get-PwshExe {
    $cmd = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    throw "No pwsh (PowerShell 7+) executable found on PATH."
}

function Test-BytesEqual {
    param([byte[]]$A, [byte[]]$B)
    if ($null -eq $A -and $null -eq $B) { return $true }
    if ($null -eq $A -or $null -eq $B) { return $false }
    if ($A.Length -ne $B.Length) { return $false }
    return [System.BitConverter]::ToString($A) -eq [System.BitConverter]::ToString($B)
}

$exitCode = 0
$script:ExecError = $null
$catalogResult = [ordered]@{
    checked = $false
    stale   = $false
    message = ''
}
$changelogResult = [ordered]@{
    checked = $false
    stale   = $false
    message = ''
    missing = @()
}
$auditResult = $null
$auditExitCode = $null

$catalogPath = Join-Path $RepoRoot 'CATALOG.md'
$originalCatalogBytes = $null
$catalogExistedBefore = $false

try {
    $pwshExe = Get-PwshExe

    $catalogScript = Join-Path $RepoRoot 'scripts/generate-catalog.ps1'
    $auditScript   = Join-Path $RepoRoot 'scripts/audit.ps1'
    if (-not (Test-Path -LiteralPath $catalogScript)) { throw "not found: $catalogScript" }
    if (-not (Test-Path -LiteralPath $auditScript))   { throw "not found: $auditScript" }

    # -----------------------------------------------------------------------
    # Check 1: CATALOG.md staleness relative to the manifest.json on disk.
    # -----------------------------------------------------------------------
    $catalogExistedBefore = Test-Path -LiteralPath $catalogPath
    if ($catalogExistedBefore) {
        $originalCatalogBytes = [System.IO.File]::ReadAllBytes($catalogPath)
    }

    try {
        & $pwshExe @('-NoProfile', '-File', $catalogScript, '-TargetDir', $RepoRoot, '-Force') | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw "generate-catalog.ps1 -Force failed (exit $LASTEXITCODE)."
        }
        $regeneratedBytes = if (Test-Path -LiteralPath $catalogPath) {
            [System.IO.File]::ReadAllBytes($catalogPath)
        } else { $null }

        $catalogResult.checked = $true
        if (-not $catalogExistedBefore) {
            $catalogResult.stale = $true
            $catalogResult.message = 'CATALOG.md did not exist and was generated fresh — run generate-catalog.ps1 -Force and commit it.'
        }
        elseif (-not (Test-BytesEqual $originalCatalogBytes $regeneratedBytes)) {
            $catalogResult.stale = $true
            $catalogResult.message = 'CATALOG.md is stale relative to manifest.json — run: pwsh ./scripts/generate-catalog.ps1 -Force'
        }
        else {
            $catalogResult.message = 'CATALOG.md is up to date.'
        }
    }
    finally {
        # Working tree safety: always restore CATALOG.md's original bytes,
        # regardless of the check's outcome or any exception above.
        if ($catalogExistedBefore) {
            [System.IO.File]::WriteAllBytes($catalogPath, $originalCatalogBytes)
        }
        elseif (Test-Path -LiteralPath $catalogPath) {
            Remove-Item -LiteralPath $catalogPath -Force -ErrorAction SilentlyContinue
        }
    }

    # -----------------------------------------------------------------------
    # Check 3: CHANGELOG.md carries a section for every release tag.
    # Read-only — no regeneration, so no working-tree restoration is needed.
    # -----------------------------------------------------------------------
    $changelogPath = Join-Path $RepoRoot 'CHANGELOG.md'
    $tags = @(git -C $RepoRoot tag -l 'v*' --sort=v:refname 2>$null | Where-Object { $_.Trim() -ne '' })

    if ($tags.Count -eq 0) {
        # Untagged repo: the whole history lives under [Unreleased] by design.
        $changelogResult.checked = $true
        $changelogResult.message = 'No release tags — nothing to assert.'
    }
    elseif (-not (Test-Path -LiteralPath $changelogPath)) {
        $changelogResult.checked = $true
        $changelogResult.stale = $true
        $changelogResult.missing = $tags
        $changelogResult.message = 'CHANGELOG.md is missing — run: pwsh ./scripts/Generate-Changelog.ps1'
    }
    else {
        $changelogText = [System.IO.File]::ReadAllText($changelogPath)
        # Ordinal, culture-invariant containment — section headers are literal.
        $missing = @($tags | Where-Object {
            -not $changelogText.Contains(("## [{0}]" -f $_.TrimStart('v')), [StringComparison]::Ordinal)
        })

        $changelogResult.checked = $true
        $changelogResult.missing = $missing
        if ($missing.Count -gt 0) {
            $changelogResult.stale = $true
            $changelogResult.message = "CHANGELOG.md has no section for: $($missing -join ', ') — run: pwsh ./scripts/Generate-Changelog.ps1"
        }
        else {
            $changelogResult.message = "All $($tags.Count) release tag(s) documented."
        }
    }

    # -----------------------------------------------------------------------
    # Check 2: audit.ps1 (covers manifest freshness, frontmatter, category,
    # installed-from, secrets, catalog parity, mirror-gap, diagrams).
    # -----------------------------------------------------------------------
    $auditJsonRaw = & $pwshExe @('-NoProfile', '-File', $auditScript, '-RepoRoot', $RepoRoot, '-Json')
    $auditExitCode = $LASTEXITCODE
    $auditResult = ($auditJsonRaw -join "`n") | ConvertFrom-Json
}
catch {
    $script:ExecError = $_
    $exitCode = 2
}

# ---------------------------------------------------------------------------
# Combine results
# ---------------------------------------------------------------------------
if ($exitCode -ne 2) {
    if ($null -eq $auditExitCode) {
        $exitCode = 2
        if (-not $script:ExecError) {
            $script:ExecError = "audit.ps1 did not report an exit code."
        }
    }
    elseif ($auditExitCode -eq 2) {
        $exitCode = 2
    }
    elseif ($catalogResult.stale -or $changelogResult.stale -or $auditExitCode -eq 1) {
        $exitCode = 1
    }
    else {
        $exitCode = 0
    }
}

$stopwatch.Stop()
$runtimeSeconds = [math]::Round($stopwatch.Elapsed.TotalSeconds, 2)

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
if ($Json) {
    [pscustomobject]@{
        summary = [pscustomobject]@{
            catalogStale    = $catalogResult.stale
            changelogStale  = $changelogResult.stale
            auditExitCode   = $auditExitCode
            auditErrors     = if ($auditResult) { $auditResult.summary.errors } else { $null }
            auditWarnings   = if ($auditResult) { $auditResult.summary.warnings } else { $null }
            auditInfo       = if ($auditResult) { $auditResult.summary.info } else { $null }
            exitCode        = $exitCode
            runtimeSeconds  = $runtimeSeconds
            executionError  = if ($script:ExecError) { "$($script:ExecError)" } else { $null }
        }
        catalog   = $catalogResult
        changelog = $changelogResult
        audit     = $auditResult
    } | ConvertTo-Json -Depth 8
}
else {
    $rows = @(
        [pscustomobject]@{
            Check  = 'catalog-staleness'
            Status = if (-not $catalogResult.checked) { 'SKIPPED' } elseif ($catalogResult.stale) { 'FAIL' } else { 'PASS' }
            Detail = $catalogResult.message
        }
        [pscustomobject]@{
            Check  = 'changelog-staleness'
            Status = if (-not $changelogResult.checked) { 'SKIPPED' } elseif ($changelogResult.stale) { 'FAIL' } else { 'PASS' }
            Detail = $changelogResult.message
        }
        [pscustomobject]@{
            Check  = 'audit.ps1'
            Status = if ($null -eq $auditExitCode) { 'SKIPPED' } elseif ($auditExitCode -eq 0) { 'PASS' } else { 'FAIL' }
            Detail = if ($auditResult) {
                "{0} error(s), {1} warning(s), {2} info; exit {3}" -f `
                    $auditResult.summary.errors, $auditResult.summary.warnings, `
                    $auditResult.summary.info, $auditExitCode
            } else { 'not run' }
        }
    )
    $rows | Format-Table -AutoSize Check, Status, Detail | Out-String -Width 200 | Write-Host

    if ($auditResult -and $auditResult.summary.errors -gt 0) {
        Write-Host 'audit error-severity findings:'
        @($auditResult.findings | Where-Object Severity -eq 'error') |
            Format-Table -AutoSize Severity, Check, Target, Message | Out-String -Width 200 | Write-Host
    }

    Write-Host ("validate: exit {0} ({1}s)" -f $exitCode, $runtimeSeconds)
    if ($exitCode -eq 2) {
        [Console]::Error.WriteLine("validate: execution failure - $($script:ExecError)")
    }
}

exit $exitCode
